### ISSUE TITLE
should be collected in one source

### ISSUE THREAD

**Issue by WendellLiu** [BOBYZH/not-citiesocial#1]
https://github.com/BOBYZH/not-citiesocial/blob/2c1febcf79bc6629486ae5597448521ac323cf9c/controllers/subscriberController.js#L11-L14

**Comment by BOBYZH** [comment]
[The possible and comprehensive patch?](https://github.com/BOBYZH/not-citiesocial/commit/1fc116ea5ce21c4ddfe9f606738165d6543805eb)

Without the video of oral test, I finally figured out this way to fix this issue with a long-term guess.

WendellLiu老師您好，抱歉過了二周多才在這邊回應有點突兀，因為這段時間先處理其他個人事情（中間還經歷電腦故障......），依照當天討論思考了一段時間後，才突然想到用拆分nodemailer設定與個別信件模板的方式，既能讓這些變數重複使用，也能使程式碼更加模組化。
